"""Run the API locally with the self-consistent fixture world wired in as the
weekly data source — every screen's endpoint answers with real-shaped data, no
Yahoo assisted pull and no nflverse download required.

    cd backend
    uv run python scripts/dev_server.py            # http://127.0.0.1:8000
    uv run python scripts/dev_server.py --port 8001

Then, in another terminal:

    cd frontend && npm run dev                     # http://localhost:5173

The Vite dev server proxies ``/api`` to :8000, so This Week, Lineup Lab,
Waiver/FA, Team Outlook and Trade Desk all render against the fixture week
(2026 week 3, Dead Parrots vs Spanish Inquisition). History is empty until a
snapshot exists — ``curl -XPOST localhost:8000/api/history/capture`` freezes the
fixture week so that screen has a row too.

This is a dev convenience, not shipped configuration: the fixture world lives
under ``tests/fixtures/weekly/`` (regenerated by ``scripts/gen_weekly_fixtures.py``)
and ``FixtureWeeklyDataSources`` is the same seam ``test_weekly_integration.py``
injects. The real deployment reads a live Yahoo assisted pull instead
(docs/adr/0001).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ``weekly_fixtures`` lives beside the tests; pytest puts it on the path via
# ``testpaths``, a plain script has to do it itself.
_TESTS_DIR = Path(__file__).resolve().parents[1] / "tests"
sys.path.insert(0, str(_TESTS_DIR))

import uvicorn  # noqa: E402

from deadparrots.app import create_app  # noqa: E402
from weekly_fixtures import FixtureWeeklyDataSources  # noqa: E402


def build_app():
    """The real ``create_app`` with only the weekly data source swapped for the
    fixture world — every other seam (sqlite, duckdb, scheduler, news) is the
    production wiring."""
    return create_app(weekly_sources=FixtureWeeklyDataSources())


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="dev_server")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args(argv)

    print(
        f"fixture-backed Dead Parrots API on http://{args.host}:{args.port}\n"
        "  screens: /api/weekly, /api/free-agents, /api/team-outlook, /api/trade-desk\n"
        "  History is empty until: curl -XPOST "
        f"http://{args.host}:{args.port}/api/history/capture"
    )
    uvicorn.run(build_app(), host=args.host, port=args.port)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
