#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Run from anywhere in the repo; everything below is relative to the repo root.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# winpath PATH → a Windows-style path explorer.exe / SmartScreen will accept.
winpath() { cygpath -w "$1" 2>/dev/null || printf '%s' "$1"; }

banner "Build & verify the Dead Parrots Dashboard Windows installer (issue #47 AC 2 + AC 3)"

# ── Stage 1: Preflight ───────────────────────────────────────────────────
stage "Preflight — the build machine has what it needs"
say "Run this on your Windows build machine, in Git Bash. Repo root:"
note "$REPO_ROOT"
say ""

fail=0

case "$(uname -s 2>/dev/null || echo unknown)" in
  MINGW*|MSYS*|CYGWIN*) note "Windows shell ✓" ;;
  *) warn "this doesn't look like Windows — the output is a Windows .exe; results may vary" ;;
esac

if [[ ! -f desktop/electron-builder.yml ]]; then
  warn "desktop/electron-builder.yml missing — check out / merge the #47 branch first"
  fail=1
else
  note "desktop/electron-builder.yml ✓"
fi

node_major="$(node --version 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/' || true)"
if [[ -z "$node_major" ]]; then
  warn "node not found on PATH — install Node 20+"
  fail=1
elif (( node_major < 20 )); then
  warn "node $(node --version) is < 20 — install Node 20+"
  fail=1
else
  note "node $(node --version) ✓"
fi

if command -v uv >/dev/null 2>&1; then
  note "uv $(uv --version 2>/dev/null || echo '(version unknown)') ✓"
else
  warn "uv not found — install from https://docs.astral.sh/uv/"
  fail=1
fi

if command -v powershell >/dev/null 2>&1 || command -v pwsh >/dev/null 2>&1; then
  note "powershell ✓  (backend freeze runs scripts/build-backend.ps1)"
else
  warn "powershell not found on PATH — needed for the backend freeze"
  fail=1
fi

if ! grep -q '"author"' desktop/package.json; then
  warn "desktop/package.json has no \"author\" field; electron-builder can refuse an NSIS build."
  if confirm "Add   \"author\": \"John Cyr <johncyrboston@gmail.com>\"   to desktop/package.json now?"; then
    node -e 'const f="desktop/package.json",fs=require("fs");const p=JSON.parse(fs.readFileSync(f));p.author="John Cyr <johncyrboston@gmail.com>";fs.writeFileSync(f,JSON.stringify(p,null,2)+"\n");'
    note "added \"author\" to desktop/package.json (commit it if you keep it)"
  else
    SKIPPED+=("add an \"author\" field to desktop/package.json if electron-builder errors")
  fi
fi

if (( fail )); then
  warn "Fix the above and re-run this wizard."
  exit 1
fi
pause "All preflight checks passed. Press Enter to continue."

# ── Stage 2: Sync backend deps ──────────────────────────────────────────
stage "Sync the backend's Python deps"
say "PyInstaller freezes whatever is in backend/.venv — sync it so nothing is missed."
step "Running:  (cd backend && uv sync)"
( cd backend && uv sync )
note "backend deps synced ✓"
pause

# ── Stage 3: Build the SPA ─────────────────────────────────────────────
stage "Build the SPA  →  frontend/dist"
step "Running:  npm --prefix frontend ci"
npm --prefix frontend ci
step "Running:  npm --prefix frontend run build"
npm --prefix frontend run build
if [[ ! -f frontend/dist/index.html ]]; then
  warn "frontend/dist/index.html is missing after the build — stop and investigate"
  exit 1
fi
note "frontend/dist/index.html ✓"
pause

# ── Stage 4: Freeze the backend ───────────────────────────────────────
stage "Freeze the backend  (PyInstaller --onedir)"
step "Running:  npm --prefix desktop ci"
npm --prefix desktop ci
step "Running:  npm --prefix desktop run build:backend    (a few minutes)"
npm --prefix desktop run build:backend

exe="desktop/backend-dist/deadparrots-backend/deadparrots-backend.exe"
if [[ ! -f "$exe" ]]; then
  warn "$exe was not produced — read the PyInstaller output above"
  exit 1
fi
note "$exe ✓"

warnfile="desktop/backend-build/warn-deadparrots-backend.txt"
if [[ -f "$warnfile" ]]; then
  say "PyInstaller lists modules it could not trace in:"
  note "$warnfile"
  say "Skim it for anything under  duckdb / polars / pyarrow / uvicorn / nflreadpy"
  say "— those are the imports that break the packaged backend at runtime. Widen the"
  say "--collect-* list in scripts/build-backend.ps1 and re-run this stage if so."
  if confirm "Open $warnfile now?"; then open_url "$(winpath "$REPO_ROOT/$warnfile")"; fi
fi

if confirm "Smoke-test the frozen backend now (start it, poll /api/health)?"; then
  tmpdata="$(mktemp -d)"
  DEADPARROTS_DATA_DIR="$tmpdata" "./$exe" --host 127.0.0.1 --port 8765 &
  bpid=$!
  ok=0
  for _ in $(seq 1 20); do
    if curl -fsS http://127.0.0.1:8765/api/health >/dev/null 2>&1; then ok=1; break; fi
    sleep 2
  done
  kill "$bpid" 2>/dev/null || true
  wait "$bpid" 2>/dev/null || true
  rm -rf "$tmpdata"
  if (( ok )); then
    note "frozen backend answered /api/health ✓"
  else
    warn "frozen backend never became healthy — check its console output and $warnfile"
    confirm "Continue anyway?" || exit 1
  fi
fi
pause

# ── Stage 5: Build the installer ──────────────────────────────────────
stage "Build the NSIS installer  →  desktop/dist/*.exe"
step "Running:  npm --prefix desktop run dist    (electron-builder --win nsis)"
npm --prefix desktop run dist

setup="$(ls -1 desktop/dist/*.exe 2>/dev/null | head -n1 || true)"
if [[ -z "$setup" ]]; then
  warn "no .exe found in desktop/dist/ — read the electron-builder output above"
  exit 1
fi
note "built:  $setup"
note "size:   $(du -h "$setup" 2>/dev/null | cut -f1 || echo '?')"
if confirm "Open the desktop/dist folder?"; then open_url "$(winpath "$REPO_ROOT/desktop/dist")"; fi
pause

# ── Stage 6: Local smoke test ─────────────────────────────────────────
stage "Local smoke test on this machine  (optional)"
say "A quick look before you carry the installer to a clean box."
if confirm "Run the installer here now?"; then
  open_url "$(winpath "$REPO_ROOT/$setup")"
  step "SmartScreen: 'Windows protected your PC' → More info → Run anyway."
  step "Finish the install, then launch 'Dead Parrots Dashboard'."
  step "Click every tab: This Week · Lineup Lab · Waiver / FA · Team Outlook · Trade Desk · History."
  pause "Press Enter once you've eyeballed the app."
  if confirm "Did all six screens render with no error banner?"; then
    note "local smoke ✓"
  else
    warn "note what broke before shipping — a clean-box run will only be worse."
  fi
else
  note "skipped the local smoke test."
fi
pause

# ── Stage 7: Clean-box verification ──────────────────────────────────
stage "Clean-box verification  (issue #47 AC 3 — the one that matters)"
say "Carry the installer to a Windows machine with NO Python and NO Node."
say "A fresh VM snapshot is ideal. Then work this checklist there:"
say ""
step "Copy  $(basename "$setup")  to the clean box and run it."
step "Click through SmartScreen; finish the install; launch the app."
step "The window opens within ~30s (the bundled backend boots first)."
step "All six screens load — This Week … History — no red error state."
step "Freshness header shows  'yahoo … never'  at first."
step "Open the embedded Yahoo window and sign in once."
step "Click 'Pull from Yahoo'. Expect four pages with per-page status shown."
step "After the pull: the yahoo chip leaves 'never'; Waiver/FA, Trade Desk and standings populate."
step "Data is under  %APPDATA%\\Dead Parrots Dashboard\\data  (parquet, sqlite, yahoo/<pull_id>/)."
say ""
pause "Press Enter once you've worked the checklist on the clean box."
ask CLEANBOX_RESULT "Clean-box result — type PASS or FAIL:"
ask CLEANBOX_NOTES  "Notes (what broke, or Enter for none):"

# ── Stage 8: Record the result ──────────────────────────────────────
stage "Record the result"
log="desktop/dist/INSTALLER-BUILD-LOG.txt"
{
  echo "Dead Parrots Dashboard — Windows installer build"
  echo "date:      $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "version:   $(node -p "require('./desktop/package.json').version" 2>/dev/null || echo '?')"
  echo "artifact:  $setup"
  echo "size:      $(du -h "$setup" 2>/dev/null | cut -f1 || echo '?')"
  echo "clean-box: ${CLEANBOX_RESULT:-not run}"
  [[ -n "${CLEANBOX_NOTES:-}" ]] && echo "notes:     $CLEANBOX_NOTES"
} > "$log"
note "wrote $log"

open_url "https://github.com/jcyr13/fantasy-football/issues/47"
open_url "https://github.com/jcyr13/fantasy-football/pull/51"

if [[ "${CLEANBOX_RESULT:-}" == "PASS" ]]; then
  step "On issue #47: tick AC 2 (npm run dist produced the .exe) and AC 3 (clean box)."
  step "Publish  $(basename "$setup")  — attach it to a GitHub release, or note its path on PR #51."
  SKIPPED+=("tick #47 AC 2 + AC 3, and publish $(basename "$setup")")
else
  warn "Clean-box run did not pass. Fix, then re-run this wizard from Stage 1."
  SKIPPED+=("clean-box verification still failing: ${CLEANBOX_NOTES:-see the checklist}")
fi

finish
