"""Loader for the self-consistent fixture world behind the issue #16
integration test (``tests/fixtures/weekly/``, regenerated by
``scripts/gen_weekly_fixtures.py``)."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

from deadparrots.weekly import AssembledWeek, assemble_week
from deadparrots.yahoo.models import (
    FreeAgentListing,
    InjuryReport,
    MatchupSnapshot,
    StandingsSnapshot,
)
from deadparrots.yahoo.normalize import (
    normalize_injuries,
    normalize_matchup,
    normalize_players,
    normalize_standings,
)
from deadparrots.yahoo.pages import YahooPage
from deadparrots.yahoo.raw import RawYahooPayload

WEEKLY_FIXTURE_DIR = Path(__file__).parent / "fixtures" / "weekly"
SEASON = 2026
WEEK = 3
AS_OF = date(2026, 9, 24)


def _rows(name: str) -> list[dict]:
    return json.loads((WEEKLY_FIXTURE_DIR / f"{name}.json").read_text())


def _yahoo(page: YahooPage) -> RawYahooPayload:
    return RawYahooPayload(
        page=page,
        source="weekly-fixture",
        fetched_at=None,  # type: ignore[arg-type]
        url=f"https://example.test/{page.value}",
        body=(WEEKLY_FIXTURE_DIR / f"{page.value}.json").read_text(encoding="utf-8"),
    )


def load_matchup() -> MatchupSnapshot:
    return normalize_matchup(_yahoo(YahooPage.MATCHUP))


def load_free_agents() -> FreeAgentListing:
    return normalize_players(_yahoo(YahooPage.PLAYERS))


def load_injuries() -> InjuryReport:
    return normalize_injuries(_yahoo(YahooPage.INJURIES))


def load_standings() -> StandingsSnapshot:
    return normalize_standings(_yahoo(YahooPage.STANDINGS))


def assemble_fixture_week(**overrides) -> AssembledWeek:
    kwargs = dict(
        matchup=load_matchup(),
        free_agents=load_free_agents(),
        injuries=load_injuries(),
        standings=load_standings(),
        player_stats_rows=_rows("player_stats"),
        snap_rows=_rows("snap_counts"),
        roster_rows=_rows("rosters"),
        schedule_rows=_rows("schedules"),
        season=SEASON,
        week=WEEK,
        as_of_date=AS_OF,
    )
    kwargs.update(overrides)
    return assemble_week(**kwargs)


class FixtureWeeklyDataSources:
    """A ``WeeklyDataSources`` backed by the fixture world, for the API tests."""

    def assemble(self, *, season: int | None = None, week: int | None = None) -> AssembledWeek:
        return assemble_fixture_week(
            season=season or SEASON, week=week or WEEK
        )
